server:
  hostname: 192.168.0.107 #159.89.22.130 192.168.0.108
  port: 1717 #
  domain: www.kui.kz
  prod: false

security:
  jwtsigningkey: secret
  enablefaker: false

ssl:
  port: :443
  certdir: certs

database:
  type: mysql
  user: root
  password: 19961711subzero
  hostname: localhost
  port: 3306
  name: niet_db

