server:
  hostname: 192.168.0.107 #159.89.22.130 192.168.0.108
  port: 80 #
  domain: www.kui.kz

security:
  jwtsigningkey: secret
  enablefaker: false

ssl:
  port: :443
  certdir: certs

database:
  type: mysql
  user: root
  password: 19961711subzero
  hostname: localhost
  port: 3306
  name: niet

mailing:
  accesskeyid: AKIAXXXXXX
  secretaccesskey: XXXXXX
  awsregion: eu-west-1
  fromemail: email
  enabletestmailer: true
